// <auto-generated />
namespace Conexion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _0103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0103));
        
        string IMigrationMetadata.Id
        {
            get { return "202112230709012_0103"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
